# AUTO-GENERATED BY CI — NE PAS ÉDITER MANUELLEMENT
# Ce fichier est mis à jour automatiquement par le workflow GitHub Actions
# avant chaque export. En développement local, la version est "dev".
class_name GameVersion
const VERSION    := "v0.8.2"
const BUILD_DATE := "2026-05-15"
