# AUTO-GENERATED BY CI — NE PAS ÉDITER MANUELLEMENT
# Ce fichier est mis à jour automatiquement par le workflow GitHub Actions
# avant chaque export. En développement local, la version est "dev".
class_name GameVersion
const VERSION    := "dev"
const BUILD_DATE := "2025-01-01"
